name: Build Server

on:
  push:
    branches:
      - main
    paths:
      - 'Server/**'
      - '.github/workflows/build-server.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
      - name: Navigate to Workspace
        run: cd ${{ github.workspace }}
      - name: Setup DotNet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x.x
          cache: true
          cache-dependency-path: Server/packages.lock.json
      - name: Restore Packages
        run: dotnet restore Server/Server.csproj --locked-mode
      - name: Build
        run: dotnet build -c Release Server/Server.csproj